# 변수 정의

In [1]:
a = 1; print(type(a))

<class 'int'>


### 여기서 equal sign은 '같다'가 아니라 왼쪽의 variable에 오른쪽의 value/content를 assign 하는 기호이다

In [2]:
a = 1
b = 2
a
b

2

In [3]:
a = 1
b = 2
print(a)
print(b)

1
2


1. cell을 구분해 적을 수도 있고, 한 cell 안에서 여러 줄을 나누어 적을 수도 있다
2. print(a)와 같이 강제로 그 값을 출력하는 것이 아니라 a만 적어 그 값을 볼 수도 있지만 만약 a variable과 b variable이 각각 그 순서대로 한 cell 안에서 다른 줄로 적혔을 때는 마지막 변수인 b의 값만 나타난다

### number 형태의 variable에는 정수 형태인 int와 소수점 형태인 float이 있다

In [4]:
a = 1; a = float(a); print(type(a))

<class 'float'>


위의 line에서 a = 1 로 int'였'으며 a = float(a) 로 float으로 다시 값이 할당되었다 이 때 print(a)의 값은? 1.0이 나올 것

In [5]:
print(a)

1.0


In [6]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


### variable에는 string 형태, 즉 문자열 또한 있다 이것은 single or double quote로 만든다

In [7]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


1. string은 number처럼 하나의 entity로 중요한 것보다 그 '순서'가 굉장히 중요하다
2. 따라서 string variable에서 index, 특정 순서의 문자를 불러와야 할 필요가 있고 이는 a[1] 과 같은 형태로 쓴다
3. 주의해야 할 건 string의 첫 번째 문자를 불러오고자 할 때는 [1]이 아닌 [0] 을 써야 하고
4. 뒤에서 index 하여 불러오고 싶을 마지막 문자를 [-1] 마지막에서 두 번째 문자를 [-2] 로 써 불러와야 한다

### list variable는 대괄호와 쉼표로 이루어지는데 그 안에 들어가는 value는 string도 num도 가능/혼재하다

In [8]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


1. string variable인 a 를 list(a)를 통해 list variable로 바꿀 수 있다
2. list 역시 그 순서가 중요하기 때문에 list처럼 [1] [2] [-1] 처럼 index하여 그 순서에 해당하는 값을 불러올 수 있다
3. 그렇다면 number variable 도 list(a)로 list variable로 바꿀 수 있을까?

In [9]:
a = 123 a = list(a); print(type(a)); print(a)

SyntaxError: invalid syntax (<ipython-input-9-f036a8c082bb>, line 1)

4. number variable은 list 함수를 통해 variable로 변환이 안 된다는 것을 확인할 수 있다

In [10]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


5. list variable은 number나 string 뿐만 아니라 list 또한 포함할 수 있다
6. 그렇다면 정의된 list variable은 스스로를 다시 포함하는 일도 가능할 것이다 아래처럼 말이다

In [11]:
a = [1, '2', [3, '4']]; print(a); a = [5, '6', a]; print(a)

[1, '2', [3, '4']]
[5, '6', [1, '2', [3, '4']]]


7. 만약 list 안에 있는 list 안에서 index를 하고 싶다면

In [12]:
print(a[-2]); print(a[-1][1]); print(a[-1][2][1])

6
2
4


8. 이런 식으로 하면 된다

### tuple variable은 list와 비슷한 형태를 가지지만 대괄호가 아닌 소괄호를 통해 만들어진다

In [13]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


1. 그렇다면 list와 tuple의 차이점은 무엇인가?
2. tuple은 가변적인 list와는 달리 불변적이라고 하는데 이는 후에 더 자세히 배울 것이다

### Dictionary variable은 사전처럼 pairwise로 항상 만들어진다

In [14]:
a = {"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


1. Dictionary 역시 index가 중요하다
2. 하지만 string이나 list와는 다르게 '순서'가 아니라 dictionary 안에서 pairwise하게 다시 assign 되는 해당 index를 참조하여야 한다

## 여기까지 0307 수업 내용 및 정리

---

In [27]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [28]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])